version: "3"

services: 
    web:
        image: anshuldevops/frindly_hello:latest
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "4000:80"
        networks: 
            - webnet
    visualizer:
        image: dockersamples/visualizer:latest
        ports: 
            - "80:8080"
        volumes: 
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks: 
            - webnet
networks: 
    webnet:

